spring:
  datasource:
    url: jdbc:mariadb://sogi-shop-project.chq5rkiuqbne.ap-northeast-2.rds.amazonaws.com:3306/sogi_shop
    username: jinseok
    password: d84247f4324b4da7b6b26ddadc5b0d3a
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

  # 스프링 부트 메시지 설정 추가
  messages:
    basename: errors

# 세션 생성시 세션 value가 쿼리파라미터로 출력되는 것을 방지
server:
  servlet:
    session:
      tracking-modes: cookie

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

file:
  dir: C:/Users/이진석/Desktop/서랍/코딩/spring 연습/file/


